server: port:9090
spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    username: liukanglai
    password: archlkl
    url: jdbc:mysql://localhost:3306/thesis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
